name: CI
on:
  push:
    branches:
      - master
jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          cat > .env <<EOF
          WEB_CLIENT_ID=${{ secrets.SSO_WEB_CLIENT_ID }}
          EOF
      - run: flutter pub get
      - run: flutter build web
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: |
          cat > .env <<EOF
          WEB_CLIENT_ID=${{ secrets.SSO_WEB_CLIENT_ID }}
          EOF
      - name: Create Google Services Plist File
        env:
          GOOGLE_SERVICES_PLIST: ${{ secrets.GOOGLE_SERVICES_PLIST }}
        run: echo $GOOGLE_SERVICES_PLIST | base64 --decode > /home/runner/work/big_life_advice_but_bigger/big_life_advice_but_bigger/ios/Runner/GoogleService-Info.plist
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign
      - name: Upload iPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos
  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          cat > .env <<EOF
          WEB_CLIENT_ID=${{ secrets.SSO_WEB_CLIENT_ID }}
          EOF
      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON | base64 --decode > /home/runner/work/big_life_advice_but_bigger/big_life_advice_but_bigger/android/app/google-services.json
      - run: flutter pub get
      - run: flutter build appbundle
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-build
          path: build/app/outputs/apk/release
  deploy_web:
    name: Deploy Web to Firebase Hosting
    needs: build_web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: web-build
          path: web-build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --public web-build
        env:
          GCP_SA_KEY: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          PROJECT_ID: ${{vars.FIREBASE_PROJECT_ID}}
  beta_ios:
    name: Upload iOS Beta to Firebase App Distribution
    needs: [build_ios]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ios-build
      - name: Upload IPA
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          appId: ${{secrets.FIREBASE_IOS_APPID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: testers
          file: Runner.ipa
  beta_apk:
    name: Upload Android Beta to Firebase App Distribution
    needs: [build_apk]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: apk-build
      - name: Upload APK
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: testers
          file: app-release.aap
